services:
  - type: web
    name: travel-website
    env: java
    buildCommand: mvn clean package
    startCommand: java -jar target/TravelPackages.war
    branch: main
    buildpacks:
      - https://github.com/heroku/heroku-buildpack-java
